title: Pine
description: ğŸŒ² Indoor Infrared receiver and transmitter with temperature sensor ğŸ
url: "https://hutscape.com/pine"
parent: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://youtube.com/@sayanee
paypal: https://www.paypal.com/ncp/payment/4JU23HRF65P66
github:
  repository_url: https://github.com/hutscape/pine
  raw_content_url: https://github.com/hutscape/pine/tree/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "scripts", "firmware"]
include: ["_data"]
collections:
  code:
    output: true
    permalink: /code/:name

project:
  power: AA
  wireless: Infrared
  sensor": Temperature
  mcu: SAMD21G18

  bom-uniq: 24
  bom-total: 49
  bom-cost-sgd: 13.21
  bom-cost-usd: 9.71
  vendors: 2

  status: completed
  completion: September 2020
