title: Pine
description: ğŸŒ² Control aircon by monitoring temperature in other parts of the room ğŸ
url: "https://hutscape.com/pine"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/hutscape/pine
  raw_content_url: https://raw.githubusercontent.com/hutscape/pine/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "test", "scripts", "firmware"]
include: ["_data"]
